### ISSUE TITLE
[Suggestion] Recurring Requests

### ISSUE THREAD

**Issue by ramazansancar** [tomondre/deployments#1]
Improvements can be made for recurring API requests.

You can optimize the number of requests by filtering out the duplicate links in an array and assigning a unique value to the links.

Yes, I know that many requests are not thrown and the first time the site is entered, the request is thrown.
But saving is always good :D

> By the way, I would like to add the detail that I love the system :P

![image](https://user-images.githubusercontent.com/8878055/214244614-7c0e884b-53ee-43f5-b59e-b1072f4c2234.png)

**Comment by tomondre** [comment]
Hi @ramazansancar,
The reason why I make recurring requests is that some of my applications are either private (Celebrator) or I do not have a health check created for the application (api.tomondre / is-ok.tomondre) - therefore, the root of the application return 404/400. This was a workaround to get the active status on the page without actually calling the application.
What could be improved is to send one request with multiple endpoints so that the website does not create a request for each item in array, but only one (a batch).
Thank you for your love 😄. It was a ton of fun and a lot of learning opportunities while making the system.

**Comment by ramazansancar** [comment]
Hi @tomondre,
Wouldn't it make more sense to leave it blank instead of putting a health checker?

**Comment by tomondre** [comment]
I kinda like the asynchronous load. What I can do is to create a timeout that would set the Active status after random time.

**Comment by ramazansancar** [comment]
I actually just said it for those who don't have health checkers.
